name = "Apex"
grammar = "apex"
path_suffixes = ["cls", "trigger", "apex"]
line_comments = ["// "]
block_comment = ["/* ", " */"]

brackets = [
  { start = "{", end = "}", close = true, newline = true },
  { start = "(", end = ")", close = true, newline = false },
  { start = "[", end = "]", close = true, newline = false },
  { start = "\"", end = "\"", close = true, newline = false, not_in = ["string"] },
]
